/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Bakeries;

import java.util.Calendar;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class Bakery extends javax.swing.JFrame {
    
    //DECLARE ARRAYS TO BE USED LATER ON IN THE CODE 
    double [] bagels = new double[4];
    double [] doughnuts = new double[3];
    double [] cakes = new double[4];
    double [] pies = new double[3];
    double [] cost = new double [3];
    double [] i = new double [4];
    double [] c = new double [4];
    double [] d = new double [3];
    double [] p = new double [3];

    public Bakery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Owner = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        blueberry = new javax.swing.JCheckBox();
        plain = new javax.swing.JCheckBox();
        chocolatechip = new javax.swing.JCheckBox();
        honey = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        Honey = new javax.swing.JTextField();
        Plain = new javax.swing.JTextField();
        ChocolateChip = new javax.swing.JTextField();
        BlueBerry = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        cupcakes = new javax.swing.JCheckBox();
        redvelvet = new javax.swing.JCheckBox();
        chocolate = new javax.swing.JCheckBox();
        cheesecake = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        CupCakes = new javax.swing.JTextField();
        RedVelvet = new javax.swing.JTextField();
        Chocolate = new javax.swing.JTextField();
        CheeseCake = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        apple = new javax.swing.JCheckBox();
        pumpkin = new javax.swing.JCheckBox();
        cherry = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        Apple = new javax.swing.JTextField();
        Pumpkin = new javax.swing.JTextField();
        Cherry = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        maple = new javax.swing.JCheckBox();
        cinnamon = new javax.swing.JCheckBox();
        original = new javax.swing.JCheckBox();
        Maple = new javax.swing.JTextField();
        Cinnamon = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Original = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TotalCostBagels = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        TotalCostPies = new javax.swing.JLabel();
        TotalCostCakes = new javax.swing.JLabel();
        TotalCostDoughnuts = new javax.swing.JLabel();
        CostBagels1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        receiptTextField = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        receipt = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        piesDropMenu = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PiesIngredients = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BagelsIngredient1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        DoughnutsIngredients1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        CakesIngredients = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        bagelsDropMenu1 = new javax.swing.JComboBox();
        doughnutsDropMenu = new javax.swing.JComboBox();
        cakesDropMenu = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("Ingredients ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CupCakes", "Chocolate Cakes", "Red Velvet Cakes", "Cakes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(395, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(43, 43, 43)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 555, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(880, 700));

        jPanel1.setMaximumSize(new java.awt.Dimension(900, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(960, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Owner.setBackground(new java.awt.Color(255, 153, 153));

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setToolTipText("");
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blueberry.setText("Blue Berry ");
        blueberry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blueberryMouseClicked(evt);
            }
        });
        blueberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueberryActionPerformed(evt);
            }
        });
        jPanel9.add(blueberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        plain.setText("Plain");
        plain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plainMouseClicked(evt);
            }
        });
        plain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plainActionPerformed(evt);
            }
        });
        jPanel9.add(plain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 130, 30));

        chocolatechip.setText("Chocolate Chip");
        chocolatechip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chocolatechipMouseClicked(evt);
            }
        });
        chocolatechip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolatechipActionPerformed(evt);
            }
        });
        jPanel9.add(chocolatechip, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 30));

        honey.setText("Honey-8-Grain");
        honey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                honeyMouseClicked(evt);
            }
        });
        honey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honeyActionPerformed(evt);
            }
        });
        jPanel9.add(honey, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 130, 30));

        jLabel2.setBackground(new java.awt.Color(102, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("                        BAGELS ");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        Honey.setText("0");
        Honey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoneyMouseClicked(evt);
            }
        });
        jPanel9.add(Honey, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 60, -1));

        Plain.setText("0");
        Plain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlainMouseClicked(evt);
            }
        });
        jPanel9.add(Plain, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 60, -1));

        ChocolateChip.setText("0");
        ChocolateChip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChocolateChipMouseClicked(evt);
            }
        });
        jPanel9.add(ChocolateChip, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 60, -1));

        BlueBerry.setText("0");
        BlueBerry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlueBerryMouseClicked(evt);
            }
        });
        BlueBerry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueBerryActionPerformed(evt);
            }
        });
        jPanel9.add(BlueBerry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 60, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 300, 200));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jTextField1.setText("                                MENU");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cupcakes.setText("Cup Cakes");
        cupcakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cupcakesMouseClicked(evt);
            }
        });
        cupcakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupcakesActionPerformed(evt);
            }
        });
        jPanel12.add(cupcakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, 30));

        redvelvet.setText("Red Velvet");
        redvelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redvelvetMouseClicked(evt);
            }
        });
        redvelvet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redvelvetActionPerformed(evt);
            }
        });
        jPanel12.add(redvelvet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 30));

        chocolate.setText("Chocolate");
        chocolate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chocolateMouseClicked(evt);
            }
        });
        chocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocolateActionPerformed(evt);
            }
        });
        jPanel12.add(chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        cheesecake.setText("Cheesecake");
        cheesecake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cheesecakeMouseClicked(evt);
            }
        });
        cheesecake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesecakeActionPerformed(evt);
            }
        });
        jPanel12.add(cheesecake, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 30));

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("                        CAKES ");
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        CupCakes.setText("0");
        CupCakes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CupCakesMouseClicked(evt);
            }
        });
        CupCakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CupCakesActionPerformed(evt);
            }
        });
        jPanel12.add(CupCakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 60, -1));

        RedVelvet.setText("0");
        RedVelvet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RedVelvetMouseClicked(evt);
            }
        });
        jPanel12.add(RedVelvet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, -1));

        Chocolate.setText("0");
        Chocolate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChocolateMouseClicked(evt);
            }
        });
        jPanel12.add(Chocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, -1));

        CheeseCake.setText("0");
        CheeseCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheeseCakeMouseClicked(evt);
            }
        });
        jPanel12.add(CheeseCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 60, -1));

        jPanel7.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 300, 200));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        apple.setText("Apple");
        apple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appleMouseClicked(evt);
            }
        });
        apple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleActionPerformed(evt);
            }
        });
        jPanel11.add(apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        pumpkin.setText("Pumpkin");
        pumpkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pumpkinMouseClicked(evt);
            }
        });
        pumpkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumpkinActionPerformed(evt);
            }
        });
        jPanel11.add(pumpkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 30));

        cherry.setText("Cherry");
        cherry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cherryMouseClicked(evt);
            }
        });
        cherry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cherryActionPerformed(evt);
            }
        });
        jPanel11.add(cherry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 30));

        jLabel3.setBackground(new java.awt.Color(102, 153, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("                          PIES");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 390, -1));

        Apple.setText("0");
        Apple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppleMouseClicked(evt);
            }
        });
        jPanel11.add(Apple, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 60, -1));

        Pumpkin.setText("0");
        Pumpkin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PumpkinMouseClicked(evt);
            }
        });
        jPanel11.add(Pumpkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        Cherry.setText("0");
        Cherry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CherryMouseClicked(evt);
            }
        });
        Cherry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CherryActionPerformed(evt);
            }
        });
        jPanel11.add(Cherry, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, -1));

        jPanel7.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 300, 180));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maple.setText("Maple");
        maple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapleMouseClicked(evt);
            }
        });
        maple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapleActionPerformed(evt);
            }
        });
        jPanel10.add(maple, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        cinnamon.setText("Cinnamon");
        cinnamon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinnamonMouseClicked(evt);
            }
        });
        cinnamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinnamonActionPerformed(evt);
            }
        });
        jPanel10.add(cinnamon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 30));

        original.setText("Original/ Plain");
        original.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                originalMouseClicked(evt);
            }
        });
        original.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originalActionPerformed(evt);
            }
        });
        jPanel10.add(original, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        Maple.setText("0");
        Maple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MapleMouseClicked(evt);
            }
        });
        jPanel10.add(Maple, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 60, -1));

        Cinnamon.setText("0");
        Cinnamon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CinnamonMouseClicked(evt);
            }
        });
        jPanel10.add(Cinnamon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));
        jPanel10.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 60, -1));

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("                    DOUGHNUTS");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        Original.setText("0");
        Original.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OriginalMouseClicked(evt);
            }
        });
        jPanel10.add(Original, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 60, -1));

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 300, 180));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Cost of Pies");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 40));

        TotalCostBagels.setBackground(new java.awt.Color(102, 153, 255));
        TotalCostBagels.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalCostBagels.setText("Total Cost of Bagels");
        jPanel13.add(TotalCostBagels, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        jLabel11.setBackground(new java.awt.Color(102, 153, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total Cost of Cakes");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        jLabel12.setBackground(new java.awt.Color(102, 153, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Total Cost of Doughnuts");
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(102, 153, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Total Cost of Pies");
        jPanel18.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 40));

        jLabel14.setBackground(new java.awt.Color(102, 153, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total Cost of Bagels");
        jPanel18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        jLabel15.setBackground(new java.awt.Color(102, 153, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Total Cost of Cakes");
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        jLabel16.setBackground(new java.awt.Color(102, 153, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Total Cost of Doughnuts");
        jPanel18.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));
        jPanel18.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, 30));
        jPanel18.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 30));
        jPanel18.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, 30));

        jPanel13.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 360, 180));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(102, 153, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Total Cost of Pies");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 40));

        jLabel18.setBackground(new java.awt.Color(102, 153, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Total Cost of Bagels");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        jLabel19.setBackground(new java.awt.Color(102, 153, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Total Cost of Cakes");
        jPanel19.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        jLabel20.setBackground(new java.awt.Color(102, 153, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Total Cost of Doughnuts");
        jPanel19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));
        jPanel19.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, 30));
        jPanel19.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 30));
        jPanel19.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, 30));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setBackground(new java.awt.Color(102, 153, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Total Cost of Pies");
        jPanel20.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 210, 40));

        jLabel22.setBackground(new java.awt.Color(102, 153, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Total Cost of Bagels");
        jPanel20.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 40));

        jLabel23.setBackground(new java.awt.Color(102, 153, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Total Cost of Cakes");
        jPanel20.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 40));

        jLabel24.setBackground(new java.awt.Color(102, 153, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Total Cost of Doughnuts");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 230, 40));
        jPanel20.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 100, 30));
        jPanel20.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 110, 30));
        jPanel20.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, 30));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 360, 180));

        jPanel13.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 360, 180));

        TotalCostPies.setBackground(new java.awt.Color(204, 204, 255));
        TotalCostPies.setText("0");
        TotalCostPies.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(TotalCostPies, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, 30));

        TotalCostCakes.setBackground(new java.awt.Color(204, 204, 255));
        TotalCostCakes.setText("0");
        TotalCostCakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(TotalCostCakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 90, 30));

        TotalCostDoughnuts.setBackground(new java.awt.Color(204, 204, 255));
        TotalCostDoughnuts.setText("0");
        TotalCostDoughnuts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(TotalCostDoughnuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, 30));

        CostBagels1.setBackground(new java.awt.Color(204, 204, 255));
        CostBagels1.setText("0");
        CostBagels1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(CostBagels1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 90, 30));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 360, 180));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receiptTextField.setEditable(false);
        receiptTextField.setColumns(20);
        receiptTextField.setRows(5);
        jScrollPane1.setViewportView(receiptTextField);

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 360));

        jPanel7.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 340, 390));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(102, 153, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL");
        jPanel16.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 40));

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SUBTOTAL");
        jPanel16.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 40));

        jLabel8.setBackground(new java.awt.Color(102, 153, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("TAX");
        jPanel16.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 40));

        jLabel9.setBackground(new java.awt.Color(102, 153, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("TAX");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 40));

        Total.setBackground(new java.awt.Color(204, 204, 255));
        Total.setText("0");
        Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, 30));

        Tax.setBackground(new java.awt.Color(204, 204, 255));
        Tax.setText("0");
        Tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.add(Tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 30));

        SubTotal.setBackground(new java.awt.Color(204, 204, 255));
        SubTotal.setText("0");
        SubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.add(SubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 30));

        jPanel7.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 240, 180));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt.setText("Receipt");
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });
        jPanel17.add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 160, 40));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel17.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 110, 50));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel17.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, 40));

        jButton4.setText("Total");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));

        jPanel7.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 340, 180));

        Owner.addTab("Buyer", jPanel7);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setToolTipText("Ingredients");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 153, 255));
        jTextField3.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jTextField3.setText("                             INGREDIENTS");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel25.setBackground(new java.awt.Color(102, 255, 102));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel25.setText("GENERAL INGREDIENTS OF THE SWEETS IN SJAM'S BAKERY");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 510, 40));

        piesDropMenu.setBackground(new java.awt.Color(204, 153, 255));
        piesDropMenu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        piesDropMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apple", "Pumpkin", "Cherry" }));
        jPanel3.add(piesDropMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 130, 40));

        jPanel5.setBackground(new java.awt.Color(255, 51, 102));

        jLabel26.setBackground(new java.awt.Color(204, 204, 255));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setText("          BAGELS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 50));

        PiesIngredients.setColumns(20);
        PiesIngredients.setRows(5);
        jScrollPane2.setViewportView(PiesIngredients);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 600, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 102));

        jLabel28.setBackground(new java.awt.Color(255, 51, 102));
        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel28.setText("       DOUGHNUTS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 220, 50));

        jPanel8.setBackground(new java.awt.Color(255, 51, 102));

        jLabel29.setBackground(new java.awt.Color(204, 204, 255));
        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setText("           CAKES");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jPanel21.setBackground(new java.awt.Color(255, 51, 102));

        jLabel27.setBackground(new java.awt.Color(204, 204, 255));
        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel27.setText("             PIES ");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        BagelsIngredient1.setColumns(20);
        BagelsIngredient1.setRows(5);
        jScrollPane3.setViewportView(BagelsIngredient1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 600, -1));

        DoughnutsIngredients1.setColumns(20);
        DoughnutsIngredients1.setRows(5);
        jScrollPane4.setViewportView(DoughnutsIngredients1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 600, -1));

        CakesIngredients.setColumns(20);
        CakesIngredients.setRows(5);
        jScrollPane5.setViewportView(CakesIngredients);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 600, -1));

        jLabel30.setBackground(new java.awt.Color(204, 204, 255));
        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel30.setText("           CAKES");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bagelsDropMenu1.setBackground(new java.awt.Color(153, 102, 255));
        bagelsDropMenu1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bagelsDropMenu1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blue Berry", "Honey-8-Grain", "Plain", "Chocolate Chip" }));
        jPanel3.add(bagelsDropMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, 40));

        doughnutsDropMenu.setBackground(new java.awt.Color(204, 102, 255));
        doughnutsDropMenu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        doughnutsDropMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maple", "Cinnamon", "Original/Plain" }));
        doughnutsDropMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doughnutsDropMenuActionPerformed(evt);
            }
        });
        jPanel3.add(doughnutsDropMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 130, 40));

        cakesDropMenu.setBackground(new java.awt.Color(204, 102, 255));
        cakesDropMenu.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cakesDropMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cupcake", "Red Velvet", "Chocolate", "Cheese" }));
        jPanel3.add(cakesDropMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, 40));

        jButton1.setText("INGREDIENTS");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 30));

        jButton2.setText("INGREDIENTS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jButton3.setText("INGREDIENTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        jButton5.setText("INGREDIENTS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 640, -1, -1));

        Owner.addTab("Ingredients", jPanel3);

        jPanel1.add(Owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1012, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    
    //THIS CODE IS FOR PIES
    //IF THE DROP DOWN MENU SELECTS A TYPE OF PIE, IT DESCRIBES THE INGREDIENTS
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Pies s = new ApplePies();
        Pies p1 = new PumpkinPies();
        Pies p2 = new CherryPies();

        if (piesDropMenu.getSelectedItem() == "Apple"){ //IF IT CHOOSES APPLE 
            PiesIngredients.setText(s.describe()); //DESCRIBES APPLE PIE 
        }

        if (piesDropMenu.getSelectedItem() == "Pumpkin"){ //IF IT CHOOSES PUMPKIN
            PiesIngredients.setText(p1.describe()); //DESCRIBES PUMPKIN PIE
        }
        if (piesDropMenu.getSelectedItem() == "Cherry"){ //IF IT CHOOSES CHERRY 
            PiesIngredients.setText(p2.describe()); //DESCRIBES CHERRY PIE 
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    //THIS CODE IS FOR THE CAKES 
    ///IF THE DROP DOWN MENU SELECTS A TYPE OF CAKE, IT DESCRIBES THE INGREDIENTS
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Cakes a = new CupCakes();
        Cakes c1 = new RedVelvetCakes();
        Cakes c2 = new ChocolateCakes();
        Cakes c3 = new ChesseCakes();

        if (cakesDropMenu.getSelectedItem() == "Cupcake"){ //IF IT CHOOSES CUPCAKE 
            CakesIngredients.setText(a.describe()); //DESCRIBES CUPCAKE 
        }

        if (cakesDropMenu.getSelectedItem() == "Red Velvet"){ //IF IT CHOOSES REDVELVELT
            CakesIngredients.setText(c1.describe()); //DESCRIBES REDVELET CAKE 
        }
        if (cakesDropMenu.getSelectedItem() == "Chocolate"){ //IF IT CHOOSES CHOCOLATE 
            CakesIngredients.setText(c2.describe()); //DESCRIBES CHOCOLATE CAKE 
        }
        if (cakesDropMenu.getSelectedItem() == "Cheese"){ //IF IT CHOOSES CHEESE 
            CakesIngredients.setText(c3.describe()); //DESCRIBES CHEESE CAKE 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //THIS CODE IS FOR THE DOUGHNUTS 
    ///IF THE DROP DOWN MENU SELECTS A TYPE OF DOUGHNUT, IT DESCRIBES THE INGREDIENTS
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Doughnuts a = new MapleDoughnuts();
        Doughnuts d1 = new CinnamonDoughnuts();
        Doughnuts d2 = new PlainDoughnuts();
        if (doughnutsDropMenu.getSelectedItem() == "Maple"){ //IF IT CHOOSES MAPLE 
            DoughnutsIngredients1.setText(a.describe()); //DESCRIBES MAPLE DOUGHNUT
        }

        if (doughnutsDropMenu.getSelectedItem() == "Cinnamon"){ //IF IT CHOOSES CINNAMON 
            DoughnutsIngredients1.setText(d1.describe()); //DESCRIBES CINNAMON DOUGHNUT
        }
        if (doughnutsDropMenu.getSelectedItem() == "Original/Plain"){ //IF IT CHOOSES ORIGINAL/PLAIN
            DoughnutsIngredients1.setText(d2.describe()); //DESCRIBES ORIGINAL DOUGHNUT 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_jButton1ActionPerformed

     //THIS CODE IS FOR THE BAGELS 
    ///IF THE DROP DOWN MENU SELECTS A TYPE OF BAGEL, IT DESCRIBES THE INGREDIENTS
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Bagels b = new PlainBagels ();
        Bagels b1 = new BlueberryBagels();
        Bagels b2 = new ChocolateChipBagels();
        Bagels b3 = new HoneyGrainBagels();
        if (bagelsDropMenu1.getSelectedItem() == "Plain"){ //IF IT CHOOSES PLAIN BAGELS 
            BagelsIngredient1.setText(b.describe()); //DESCRIBES PLAIN BAGEL
        }
        if (bagelsDropMenu1.getSelectedItem() == "Blue Berry"){ //IF IT CHOOSES BLUEBERRY BAGELS
            BagelsIngredient1.setText(b1.describe()); //DESCRIBES BLUE BERRY BAGEL
        }
        if (bagelsDropMenu1.getSelectedItem() == "Chocolate Chip"){ //IF IT CHOOSES CHOCOLATE CHIP BAGELS
            BagelsIngredient1.setText(b2.describe()); //DESCRIBES CHOCOLATECHIP BAGEL
        }
        if (bagelsDropMenu1.getSelectedItem() == "Honey-8-Grain"){ //IF IT CHOOSES HONEY-8-GRAIN BAGELS 
            BagelsIngredient1.setText(b3.describe()); //DESCRIBES HONEY BAGEL 
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void doughnutsDropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doughnutsDropMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_doughnutsDropMenuActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       //TAKES THE COST OF BAGELS, CAKES, DOUGHNUTS, AND PIES ADDS THEM
       // PUTS THEM IN THE TOTAL ON THE SCREEN
        
        c[0] = Double.parseDouble(CostBagels1.getText());
        c[1] = Double.parseDouble(TotalCostCakes.getText());
        c[2] = Double.parseDouble(TotalCostDoughnuts.getText());
        c[3] = Double.parseDouble(TotalCostPies.getText());
        
        //ADDS THEM 
        double total = c[0] + c[1] + c[2] + c[3];
        //OUTPUT ON SCREEN
        String totalCost = String.format("%.2f",total);
        //TAX
        double tax = total* 0.13;
        String totalTax = String.format("%.2f", tax);
        Tax.setText(totalTax);
        SubTotal.setText(totalCost);
        double totalMoney = total + tax;
        //OUTPUT TOTAL
        String totalMoneyy = String.format("%.2f", totalMoney);

        Total.setText(totalMoneyy);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        //WHEN THE RESET BUTTON IS CLICKED, IT CLEARS ALL INPUTS AND SETS IT AS A DEFAULT OF ZERO 
        TotalCostCakes.setText("0");
        Total.setText("0");
        TotalCostPies.setText("0");
        TotalCostDoughnuts.setText("0");
        Tax.setText("0");
        SubTotal.setText("0");
        Total.setText("0");
        BlueBerry.setText("0");
        Honey.setText("0");
        Plain.setText("0");
        ChocolateChip.setText("0");
        Maple.setText("0");
        Cinnamon.setText("0");
        Original.setText("0");
        CupCakes.setText("0");
        RedVelvet.setText("0");
        Chocolate.setText("0");
        CheeseCake.setText("0");
        Apple.setText("0");
        Pumpkin.setText("0");
        Cherry.setText("0");
        blueberry.setSelected(false);
        honey.setSelected(false);
        plain.setSelected(false);
        chocolatechip.setSelected(false);
        maple.setSelected(false);
        cinnamon.setSelected(false);
        original.setSelected(false);
        cupcakes.setSelected(false);
        redvelvet.setSelected(false);
        chocolate.setSelected(false);
        cheesecake.setSelected(false);
        apple.setSelected(false);
        pumpkin.setSelected(false);
        cherry.setSelected(false);
        receiptTextField.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        //EXITS THE PROGRAM WHEN EXIT IS CLICKED 
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
//CHANGE STRING TO DOUBLE
        bagels[0] = Double.parseDouble(BlueBerry.getText());
        bagels[1] = Double.parseDouble(Honey.getText());
        bagels[2] = Double.parseDouble(Plain.getText());
        bagels[3] = Double.parseDouble(ChocolateChip.getText());
//CHANGE STRING TO DOUBLE
        doughnuts[0] = Double.parseDouble(Maple.getText());
        doughnuts[1] = Double.parseDouble(Cinnamon.getText());
        doughnuts[2] = Double.parseDouble(Original.getText());
//CHANGE STRING TO DOUBLE
        cakes[0] = Double.parseDouble(CupCakes.getText());
        cakes[1] = Double.parseDouble(RedVelvet.getText());
        cakes[2] = Double.parseDouble(Chocolate.getText());
        cakes[3] = Double.parseDouble(CheeseCake.getText());
//CHANGE STRING TO DOUBLE
        pies[0] = Double.parseDouble(Apple.getText());
        pies[1] = Double.parseDouble(Pumpkin.getText());
        pies[2] = Double.parseDouble(Cherry.getText());
        cost[0] = Double.parseDouble(Tax.getText());
        cost[1] = Double.parseDouble(SubTotal.getText());
        cost[2] = Double.parseDouble(Total.getText());
        int refs =  1325 + (int)(Math.random()*4238);
//GET TIME 
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());

        //OUTPUT RECeIPT 
        receiptTextField.append(" \t\n SJAM Bakery: \n\n" +
            "Reference:\t\t" + refs+
            "\nBlueBerry Bagel:\t" + bagels[0] +
            "\nHoney Bagel:\t\t " + bagels[1] +
            "\nPlain Bagel:\t\t " + bagels[2] +
            "\nChocolateChip Bagel:\t" + bagels[3] +

            "\n----------------------------------------------------\t\t"+

            "\nMaple:\t\t " + doughnuts[0] +
            "\nCinnamon:\t\t " + doughnuts[1] +
            "\nOriginal:\t\t " + doughnuts[2] +
            "\n----------------------------------------------------\t\t"+
            "\nCupcakes:\t\t " + cakes[0] +
            "\nRedVelvet:\t\t " + cakes[1] +
            "\nChocolate:\t\t " + cakes[2] +
            "\nCheeseCake :\t\t " + cakes[3] +
            "\n----------------------------------------------------\t\t"+
            "\nApple:\t\t " + pies[0] +
            "\nPumpkin:\t\t " + pies[1] +
            "\nCherry:\t\t " + pies[2] +

            "\n----------------------------------------------------\t\t"+
            "\nTax:\t\t"+ cost[0] +
            "\nSub Total:\t\t"+ cost[1] +
            "\nTotal:\t\t"+ cost[2] +

            "\n----------------------------------------------------\t\t"+

            "\nDate: " + Tdate.format(timer.getTime()) +
            "\tTime: " + tTime.format(timer.getTime()) +
            "\n\nThank you");
    }//GEN-LAST:event_receiptActionPerformed

    private void OriginalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OriginalMouseClicked
       //SET NULL 
        Original.setText(null);
    }//GEN-LAST:event_OriginalMouseClicked

    private void CinnamonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CinnamonMouseClicked
       //SET NULL 
        Cinnamon.setText(null);
    }//GEN-LAST:event_CinnamonMouseClicked

    private void MapleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MapleMouseClicked
      //SET NULL
        Maple.setText(null);
    }//GEN-LAST:event_MapleMouseClicked

    private void originalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originalActionPerformed
       //SHOW DIALOG WHEN INPUT IS NOT INTEGER
        if (Character.isLetter(Original.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_originalActionPerformed

    private void originalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_originalMouseClicked
       //GET THE TOTAL COST OF DOUGHNUTS
        double oOriginal = Double.parseDouble(TotalCostDoughnuts.getText());
        //GET THE TOTAL QUNATITY OF ORIGINAL DOUGHNUTS
        double originall = Double.parseDouble(Original.getText());
        double costOriginal = 1.00;
        //IF CHECKBOX IS SELCTED, THEN ADD THE TOTAL COST OF ORIGINAL DOUGHNUTS TO THE TOTAL COST OF DOUGHNUTS
        if (original.isSelected()){
            d[2] = (originall * costOriginal ) + oOriginal;
            String cDoughnuts = String.format("%.2f", d[2]);
            TotalCostDoughnuts.setText(cDoughnuts);
        }
    }//GEN-LAST:event_originalMouseClicked

    private void cinnamonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinnamonMouseClicked
        //GET THE TOTAL COST OF DOUGHNUTS
        double cCinnamon = Double.parseDouble(TotalCostDoughnuts.getText());
        //GET THE TOTAL QUNATITY OF CINNAMON DOUGHNUTS
        double cinnamons = Double.parseDouble(Cinnamon.getText());
        double costCinnamon = 1.00;
        if (cinnamon.isSelected()){ //IF CHECKBOX IS SELCTED, THEN ADD THE TOTAL COST OF CINNAMON DOUGHNUTS TO THE TOTAL COST OF DOUGHNUTS
            d[1] = (cinnamons * costCinnamon ) + cCinnamon;
            String bDoughnuts = String.format("%.2f", d[1]);
            TotalCostDoughnuts.setText(bDoughnuts);

        }
    }//GEN-LAST:event_cinnamonMouseClicked

    private void mapleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapleMouseClicked
        //GET THE TOTAL COST OF DOUGHNUTS
        double mMaple = Double.parseDouble(TotalCostDoughnuts.getText());
        //GET THE TOTAL QUNATITY OF MAPLE DOUGHNUTS
        double maples = Double.parseDouble(Maple.getText());
        double costMaple = 1.00;
        
        //IF CHECKBOX IS SELCTED, THEN ADD THE TOTAL COST OF MAPLE DOUGHNUTS TO THE TOTAL COST OF DOUGHNUTS
        if (maple.isSelected()){
            d[0] = (maples * costMaple ) + mMaple;
            String aDoughnuts = String.format("%.2f", d[0]);
            TotalCostDoughnuts.setText(aDoughnuts);

        }
    }//GEN-LAST:event_mapleMouseClicked

    private void CherryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CherryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CherryActionPerformed

    private void CherryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CherryMouseClicked
        //SET NULL
        Cherry.setText(null);
    }//GEN-LAST:event_CherryMouseClicked

    private void PumpkinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PumpkinMouseClicked
        //SET NULL
        Pumpkin.setText(null);
    }//GEN-LAST:event_PumpkinMouseClicked

    private void AppleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppleMouseClicked
        //SET NULL
        Apple.setText(null);
    }//GEN-LAST:event_AppleMouseClicked

    private void cherryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cherryActionPerformed
      //IF THE USER DID NOT INPUT an INTEGER THAN SHOW DIALOG 
        if (Character.isLetter(Cherry.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_cherryActionPerformed

    private void cherryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cherryMouseClicked
        //GET THE TOTAL COST OF PIES 
        double cCherry = Double.parseDouble(TotalCostPies.getText());
        //GET THE TOTAL QUANTITY OF CHERRY 
        double cherry1 = Double.parseDouble(Cherry.getText());
        double costCherry = 4.50;
        //IF THE CHERRY CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF CHERRY PIES TO THE TOTAL COST OF PIES 
        if (cherry.isSelected()){
            p[2] = (cherry1 * costCherry ) + cCherry;
            String cPie = String.format("%.2f", p[2]);
            TotalCostPies.setText(cPie);
        }
    }//GEN-LAST:event_cherryMouseClicked

    private void pumpkinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pumpkinMouseClicked
       //GET THE TOTAL COST OF PIES 
        double pPumpkin = Double.parseDouble(TotalCostPies.getText());
        //GET THE TOTAL QUANTITY OF PUMPKIN 
        double pumpkin1 = Double.parseDouble(Pumpkin.getText());
        double costPumpkin = 4.50;
        //IF THE PUMPKIN CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF PUMPKIN PIES TO THE TOTAL COST OF PIES 
        if (pumpkin.isSelected()){
            p[1] = (pumpkin1 * costPumpkin ) + pPumpkin;
            String bPie = String.format("%.2f", p[1]);
            TotalCostPies.setText(bPie);
        }
    }//GEN-LAST:event_pumpkinMouseClicked

    private void appleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appleMouseClicked
        //GET THE TOTAL COST OF PIES 
        double aApple = Double.parseDouble(TotalCostPies.getText());
        //GET THE TOTAL QUANTITY OF APPLE 
        double apple1 = Double.parseDouble(Apple.getText());
        double costApple = 4.50;
        
        //IF THE APPLE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF APPLE PIES TO THE TOTAL COST OF PIES 
        if (apple.isSelected()){
            p[0] = (apple1 * costApple ) + aApple;
            String aPie = String.format("%.2f", p[0]);
            TotalCostPies.setText(aPie);
        }
    }//GEN-LAST:event_appleMouseClicked

    private void CheeseCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheeseCakeMouseClicked
        //SET TO NULL
        CheeseCake.setText(null);

    }//GEN-LAST:event_CheeseCakeMouseClicked

    private void ChocolateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChocolateMouseClicked
        //SET TO NULL
        Chocolate.setText(null);
    }//GEN-LAST:event_ChocolateMouseClicked

    private void RedVelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RedVelvetMouseClicked
        //SET TO NULL
        RedVelvet.setText(null);
    }//GEN-LAST:event_RedVelvetMouseClicked

    private void CupCakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CupCakesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CupCakesActionPerformed

    private void CupCakesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CupCakesMouseClicked
        //SET TO NULL
        CupCakes.setText(null);
    }//GEN-LAST:event_CupCakesMouseClicked

    private void cheesecakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cheesecakeMouseClicked
        //GET THE INPUT FOR THE TOTAL COST OF CAKES 
        double cCheeseCake = Double.parseDouble(TotalCostCakes.getText());
        //GETS THE INPUT FOR THE TOTAL QUANTITY FOR THE CHEESECAKE TEXTBOX 
        double cheeseCake = Double.parseDouble(CheeseCake.getText());
        double costCheeseCake = 10.00;
        
        //IF THE CHEESECAKE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF CHEESECAKE TO THE TOTAL COST OF CAKES 
        if (cheesecake.isSelected()){
            c[3] = (cheeseCake * costCheeseCake ) + cCheeseCake;
            String dCakes = String.format("%.2f", c[3]);
            TotalCostCakes.setText(dCakes);

        }
    }//GEN-LAST:event_cheesecakeMouseClicked

    private void chocolateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocolateMouseClicked
        //GET THE INPUT FOR THE TOTAL COST OF CAKES
        double cChocolate = Double.parseDouble(TotalCostCakes.getText());
       //GETS THE INPUT FOR THE TOTAL QUANTITY FOR THE CHOCOLATE CHIP CAKES TEXTBOX 
        double chocolate1 = Double.parseDouble(Chocolate.getText());
        double costChocolate = 10.00;
        //IF THE CHOCOLATE CHIP CAKE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF CHOCOLATE CHIP CAKES TO THE TOTAL COST OF CAKES
        if (chocolate.isSelected()){
            c[2] = (chocolate1 * costChocolate ) + cChocolate;
            String cCakes = String.format("%.2f", c[2]);
            TotalCostCakes.setText(cCakes);

        }
    }//GEN-LAST:event_chocolateMouseClicked

    private void redvelvetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redvelvetMouseClicked
        //GETS THE INPUT FOR THE TOTAL COST OF CAKES 
        double rRedvelvet = Double.parseDouble(TotalCostCakes.getText());
       //GETS THE INPUT FOR THE TOTAL QUANTITY FOR RED VELVET TEXTBOX
        double redVelvet1 = Double.parseDouble(RedVelvet.getText());
        double costRedVelvet = 10.00;
        
        //IF THE REDVELVET CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF REDVELVET CAKES TO THE TOTAL CAKES 
        if (redvelvet.isSelected()){
            c[1] = (redVelvet1 * costRedVelvet ) + rRedvelvet;
            String bCakes = String.format("%.2f", c[1]);
            TotalCostCakes.setText(bCakes);

        }
    }//GEN-LAST:event_redvelvetMouseClicked

    private void cupcakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupcakesActionPerformed
      //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(CupCakes.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_cupcakesActionPerformed

    private void cupcakesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cupcakesMouseClicked
        //GET THE INPUT FOR THE TOTAL COST OF CAKES 
        double cCupcakes = Double.parseDouble(TotalCostCakes.getText());
        //GET THE INPUT FOR THE TOTAL QUANTITY OF CUPCAKES 
        double cupcakes1 = Double.parseDouble(CupCakes.getText());
        double costCupcakes = 10.00;
        
        //IF THE CHECKBOX IS CLICKED, THEN ADD THE TOTAL COST OF CUPCAKES TO THE TOTAL COST OF CAKES 
        if (cupcakes.isSelected()){
            c[0] = (cupcakes1 * costCupcakes ) + cCupcakes;
            String aCakes = String.format("%.2f", c[0]);
            TotalCostCakes.setText(aCakes);

        }
    }//GEN-LAST:event_cupcakesMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BlueBerryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueBerryActionPerformed
        
    }//GEN-LAST:event_BlueBerryActionPerformed

    private void BlueBerryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlueBerryMouseClicked
        //SET TO NULL WHEN TEXTBOX IS CLICKED (SO THE USER DOES NOT NEED TO DELETE 0) 
        BlueBerry.setText(null);
        
    }//GEN-LAST:event_BlueBerryMouseClicked

    private void ChocolateChipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChocolateChipMouseClicked
        //SET TO NULL WHEN TEXTBOX IS CLICKED
        ChocolateChip.setText(null);
    }//GEN-LAST:event_ChocolateChipMouseClicked

    private void PlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlainMouseClicked
        //SET TO NULL WHEN TEXTBOX IS CLICKED
        Plain.setText(null);
    }//GEN-LAST:event_PlainMouseClicked

    private void HoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoneyMouseClicked
        //SET TO NULL WHEN TEXTBOX IS CLICKED
        Honey.setText(null);
    }//GEN-LAST:event_HoneyMouseClicked

    private void honeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_honeyMouseClicked
        //GETS THE INPUT FOR THE TOTAL COST OF HONEY BAGELS 
        double hHoney = Double.parseDouble(CostBagels1.getText());
        
        //GEST THE INPUT FOR THE HONEY BAGEL TEXTBOX 
        double Honey1 = Double.parseDouble(Honey.getText());
        double costHoney = 1.25;

        //IF THE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF HONEY BAGEL TO THE TOTAL COST OF BAGELS
        if (honey.isSelected()){
            i[1] = (Honey1 * costHoney) + hHoney;
            String bBagels = String.format("%.2f", i[1]);
            CostBagels1.setText(bBagels);
            // Honey.setText(hBagels);
        }
    }//GEN-LAST:event_honeyMouseClicked

    private void chocolatechipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chocolatechipMouseClicked
        //GETS THE INPUT FOR THE TOTAL COST OF CHOCOALTECHIP BAGELS 
        double cChocolatechip = Double.parseDouble(CostBagels1.getText());
        //GEST THE INPUT FOR THE CHOCOLATECHIP BAGEL TEXTBOX 
        double chocolatechip1 = Double.parseDouble(ChocolateChip.getText());
        double costChocolateChip = 1.25;

        //IF THE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF THE CHOCOLATECHIP BAGEL TO THE TOTAL COST
        if (chocolatechip.isSelected()){
            i[3] = (chocolatechip1 * costChocolateChip) + cChocolatechip;
            String dBagels = String.format("%.2f", i[3]);
            CostBagels1.setText(dBagels);
        }
    }//GEN-LAST:event_chocolatechipMouseClicked

    private void plainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plainMouseClicked
        //GETS THE INPUT TOTAL COST OF BAGELS 
        double pPlain = Double.parseDouble(CostBagels1.getText());
        
        //GETS THE INPUT OF THE PLAIN BAGEL TEXT BOX 
        double plain1 = Double.parseDouble(Plain.getText());
        double costPlain = 1.25;

        //IF THE CHECKBOX IS SELECTED, THEN ADD THE TOTAL COST OF PLAIN BAGEL TO THE TOTAL COST 
        if (plain.isSelected()){
            i[2] = (plain1 * costPlain) + pPlain;
            String cBagels = String.format("%.2f", i[2]);
            CostBagels1.setText(cBagels);
        }
    }//GEN-LAST:event_plainMouseClicked

    private void blueberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueberryActionPerformed
       //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(BlueBerry.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }           
  
    }//GEN-LAST:event_blueberryActionPerformed

    private void blueberryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueberryMouseClicked
        //OUTPUTS THE TOTAL AMOUNT OF BAGEL COST  
        
        double bBlueberry = Double.parseDouble(CostBagels1.getText());
        double blueBerry1 = Double.parseDouble(BlueBerry.getText());
        double costBlueBerry = 1.25;

        //IF THE CHECKBOX IS SELECTED, THEN CALCULATE THE TOTAL COST USING THE QUANTITY
        if (blueberry.isSelected()){
            i[0] = (blueBerry1 * costBlueBerry) + bBlueberry;
            String aBagels = String.format("%.2f", i[0]);
            CostBagels1.setText(aBagels);
            // BlueBerry.setText(cBagels);

        }
    }//GEN-LAST:event_blueberryMouseClicked

    private void honeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honeyActionPerformed
       //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Honey.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_honeyActionPerformed

    private void plainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plainActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Plain.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
       
    }//GEN-LAST:event_plainActionPerformed

    private void chocolatechipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolatechipActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(ChocolateChip.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_chocolatechipActionPerformed

    private void mapleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapleActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Maple.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_mapleActionPerformed

    private void cinnamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinnamonActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Cinnamon.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_cinnamonActionPerformed

    private void redvelvetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redvelvetActionPerformed
       //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(RedVelvet.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_redvelvetActionPerformed

    private void chocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocolateActionPerformed
       //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Chocolate.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_chocolateActionPerformed

    private void cheesecakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesecakeActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(CheeseCake.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_cheesecakeActionPerformed

    private void appleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleActionPerformed
       //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Apple.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_appleActionPerformed

    private void pumpkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumpkinActionPerformed
        //IF INTEGER IS NOT INPUTTED, OUTPUT DIALOG ON SCREEN
        if (Character.isLetter(Pumpkin.getText().charAt(0))){
           JOptionPane.showMessageDialog(jPanel7, "Input an integer");
       }        
    }//GEN-LAST:event_pumpkinActionPerformed

    public static void main(String args[]) throws FileNotFoundException {

    
     /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bakery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bakery().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Apple;
    public javax.swing.JTextArea BagelsIngredient1;
    public javax.swing.JTextField BlueBerry;
    public javax.swing.JTextArea CakesIngredients;
    public javax.swing.JTextField CheeseCake;
    public javax.swing.JTextField Cherry;
    public javax.swing.JTextField Chocolate;
    public javax.swing.JTextField ChocolateChip;
    public javax.swing.JTextField Cinnamon;
    public javax.swing.JLabel CostBagels1;
    public javax.swing.JTextField CupCakes;
    public javax.swing.JTextArea DoughnutsIngredients1;
    public javax.swing.JButton Exit;
    public javax.swing.JTextField Honey;
    public javax.swing.JTextField Maple;
    public javax.swing.JTextField Original;
    public javax.swing.JTabbedPane Owner;
    public javax.swing.JTextArea PiesIngredients;
    public javax.swing.JTextField Plain;
    public javax.swing.JTextField Pumpkin;
    public javax.swing.JTextField RedVelvet;
    public javax.swing.JLabel SubTotal;
    public javax.swing.JLabel Tax;
    public javax.swing.JLabel Total;
    public javax.swing.JLabel TotalCostBagels;
    public javax.swing.JLabel TotalCostCakes;
    public javax.swing.JLabel TotalCostDoughnuts;
    public javax.swing.JLabel TotalCostPies;
    public javax.swing.JCheckBox apple;
    public javax.swing.JComboBox bagelsDropMenu1;
    public javax.swing.JCheckBox blueberry;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JComboBox cakesDropMenu;
    public javax.swing.JCheckBox cheesecake;
    public javax.swing.JCheckBox cherry;
    public javax.swing.JCheckBox chocolate;
    public javax.swing.JCheckBox chocolatechip;
    public javax.swing.JCheckBox cinnamon;
    public javax.swing.JCheckBox cupcakes;
    public javax.swing.JComboBox doughnutsDropMenu;
    public javax.swing.JCheckBox honey;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JDialog jDialog1;
    public javax.swing.JDialog jDialog2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel23;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel25;
    public javax.swing.JLabel jLabel26;
    public javax.swing.JLabel jLabel27;
    public javax.swing.JLabel jLabel28;
    public javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel30;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel11;
    public javax.swing.JPanel jPanel12;
    public javax.swing.JPanel jPanel13;
    public javax.swing.JPanel jPanel14;
    public javax.swing.JPanel jPanel15;
    public javax.swing.JPanel jPanel16;
    public javax.swing.JPanel jPanel17;
    public javax.swing.JPanel jPanel18;
    public javax.swing.JPanel jPanel19;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel20;
    public javax.swing.JPanel jPanel21;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JPanel jPanel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField28;
    public javax.swing.JTextField jTextField29;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField30;
    public javax.swing.JTextField jTextField31;
    public javax.swing.JTextField jTextField32;
    public javax.swing.JTextField jTextField33;
    public javax.swing.JTextField jTextField34;
    public javax.swing.JTextField jTextField35;
    public javax.swing.JTextField jTextField36;
    public javax.swing.JCheckBox maple;
    public javax.swing.JCheckBox original;
    public javax.swing.JComboBox piesDropMenu;
    public javax.swing.JCheckBox plain;
    public javax.swing.JCheckBox pumpkin;
    public javax.swing.JButton receipt;
    public javax.swing.JTextArea receiptTextField;
    public javax.swing.JCheckBox redvelvet;
    public javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
